name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Get Temporal docker-compose.yml
        run: wget https://raw.githubusercontent.com/temporalio/docker-compose/v1.12.0/docker-compose.yml
      - name: Start Temporal Server
        run: docker-compose up -d
      - name: Install deps
        run: npm install
      - name: Wait for Temporal Server
        run: node .scripts/wait-on-temporal.mjs
      - run: npm test
